services:
  postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=bookshop
      - POSTGRES_USER=bookshop
      - POSTGRES_DB=bookshop
    profiles:
      - postgres
